package manifest

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSavePreset_createsFile(t *testing.T) {
	dir := t.TempDir()
	p := Preset{
		Name:        "minimal",
		Description: "one unit; tls off",
		Sets: map[string]any{
			"internal_tls": false,
			"units":        1,
		},
	}
	if err := SavePreset(dir, p); err != nil {
		t.Fatalf("SavePreset: %v", err)
	}

	path := filepath.Join(dir, LocalFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !strings.Contains(string(data), "Generated by Atelier") {
		t.Errorf("expected provenance header; got:\n%s", data)
	}

	// The written file must parse back and yield the same preset via the
	// normal discovery path (primary-module "." entry).
	got, warns, err := Load(path)
	if err != nil {
		t.Fatalf("reparse: %v (warns %v)", err, warns)
	}
	presets := got.presetsForModule(PrimaryModulePath)
	if len(presets) != 1 {
		t.Fatalf("presets for '.' = %d; want 1", len(presets))
	}
	if presets[0].Name != "minimal" || presets[0].Description != "one unit; tls off" {
		t.Errorf("round-trip preset = %+v", presets[0])
	}
	if len(presets[0].Sets) != 2 {
		t.Errorf("sets = %v; want 2 entries", presets[0].Sets)
	}
}

func TestSavePreset_refusesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, LocalFileName)
	if err := os.WriteFile(path, []byte("modules: []\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	original, _ := os.ReadFile(path)

	err := SavePreset(dir, Preset{Name: "x", Sets: map[string]any{"a": 1}})
	if err == nil {
		t.Fatal("expected error when file exists")
	}
	if !errors.Is(err, fs.ErrExist) {
		t.Errorf("error should wrap fs.ErrExist; got %v", err)
	}
	// The pre-existing file must be untouched.
	after, _ := os.ReadFile(path)
	if string(after) != string(original) {
		t.Errorf("existing file was modified:\n%s", after)
	}
}

func TestSavePreset_rejectsEmptySets(t *testing.T) {
	dir := t.TempDir()
	// validate() requires >=1 entry in sets; SavePreset should surface it and
	// write nothing.
	if err := SavePreset(dir, Preset{Name: "empty", Sets: map[string]any{}}); err == nil {
		t.Fatal("expected validation error for empty sets")
	}
	if HasLocalFile(dir) {
		t.Error("no file should have been created for an invalid preset")
	}
}

func TestHasLocalFile(t *testing.T) {
	dir := t.TempDir()
	if HasLocalFile(dir) {
		t.Error("HasLocalFile true on empty dir")
	}
	if err := os.WriteFile(filepath.Join(dir, LocalFileName), []byte("modules: []\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !HasLocalFile(dir) {
		t.Error("HasLocalFile false after creating the file")
	}
}
