package importer

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/hashicorp/hcl/v2/hclwrite"
	tfjson "github.com/hashicorp/terraform-json"

	"github.com/MichaelThamm/atelier/internal/tfexec"
)

// DefaultImportsFile is the name of the generated declarative-import artifact.
const DefaultImportsFile = "imports.tf"

// importsFileHeader marks a file as Atelier-generated. Cleanup is gated on it
// so a hand-written imports.tf is never deleted.
const importsFileHeader = "# Generated by `atelier import`.\n"

// RemoveGeneratedImportsFile deletes an Atelier-generated imports artifact,
// leaving a user-authored file of the same name untouched.
//
// Called before the module is planned, which is correctness rather than tidiness:
// with `import {}` blocks present Terraform reports those resources as
// Importing, and PlannedCreates skips Importing entries, so a stale artifact
// from an earlier --dry-run would make the run find zero import candidates.
func RemoveGeneratedImportsFile(path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	if !bytes.HasPrefix(data, []byte(importsFileHeader)) {
		return // user-authored; not ours to remove
	}
	_ = os.Remove(path) // best-effort
}

// RenderImportsFile renders `import {}` blocks (Terraform 1.5+) for the given
// address→import-ID pairs, sorted by address.
//
// Atelier does not use this file to perform the import — that is done with
// `terraform import`, which is a pure state operation and so cannot touch
// infrastructure. The file exists as a reviewable, editable artifact: it is
// what a user inspects before committing to an import, and what they edit and
// retry with when a run fails part-way.
//
// The `note` lines are emitted as leading comments so the artifact explains
// itself when read in isolation.
func RenderImportsFile(ids map[string]string, note ...string) []byte {
	var sb strings.Builder
	sb.WriteString(importsFileHeader)
	sb.WriteString("#\n")
	for _, n := range note {
		sb.WriteString("# " + n + "\n")
	}
	sb.WriteString("#\n")
	sb.WriteString("# WARNING: `terraform apply` with these blocks present executes the whole\n")
	sb.WriteString("# plan, not just the imports. If this file does not cover every resource the\n")
	sb.WriteString("# module declares, apply will CREATE the ones it misses — duplicating live\n")
	sb.WriteString("# infrastructure. Check `terraform plan` reports 0 to add first.\n")
	sb.WriteString("\n")
	for _, addr := range sortedKeys(ids) {
		fmt.Fprintf(&sb, "import {\n  to = %s\n  id = %q\n}\n\n", addr, ids[addr])
	}
	return hclwrite.Format([]byte(sb.String()))
}

// PlanSummary counts the actions in a plan, separating imports from mutations.
// It is what `--dry-run` reports: Import is the work the import set covers, and
// Add is the work it does not — a non-zero Add (after discounting resource
// types that can never be imported) means the module declares resources that
// were not matched to anything live.
type PlanSummary struct {
	Import  int
	Add     int
	Change  int
	Destroy int
	// AddAddresses lists the addresses counted in Add, excluding types that
	// have no live counterpart by definition (see unimportableTypes). These
	// are the ones worth a user's attention.
	AddAddresses []string
	// UnimportableAdds counts Add entries whose type can never be imported
	// (e.g. terraform_data). They are expected and benign.
	UnimportableAdds int
}

// SummarizePlan classifies every resource change in a plan.
func SummarizePlan(plan *tfjson.Plan) PlanSummary {
	var s PlanSummary
	if plan == nil {
		return s
	}
	for _, rc := range plan.ResourceChanges {
		if rc == nil || rc.Change == nil {
			continue
		}
		// Terraform reports a planned import via Change.Importing, which may
		// accompany a NoOp or an Update action.
		if rc.Change.Importing != nil {
			s.Import++
		}
		switch {
		case rc.Change.Actions.Delete():
			s.Destroy++
		case rc.Change.Actions.Create():
			if rc.Change.Importing != nil {
				continue // being imported, not created
			}
			s.Add++
			if unimportableTypes[rc.Type] {
				s.UnimportableAdds++
				continue
			}
			s.AddAddresses = append(s.AddAddresses, rc.Address)
		case rc.Change.Actions.Update():
			if rc.Change.Importing == nil {
				s.Change++
			}
		}
	}
	return s
}

// varArgs renders a map of query variables as `-var k=v` arguments so a
// reported command can be copy-pasted.
func varArgs(vars map[string]string) string {
	var sb strings.Builder
	for _, k := range sortedKeys(vars) {
		fmt.Fprintf(&sb, " -var %s=%s", k, vars[k])
	}
	return sb.String()
}

// BuildImportIDs turns matched live objects into the address→import-ID set to
// import, and reports the matches it could not resolve.
//
// Two filters apply, and the difference between them matters:
//
//   - A match whose address is not in `creates` is **skipped silently**. It is
//     already in state, so there is nothing to import. This is what makes
//     `atelier import` safely re-runnable: a second run matches the same live
//     objects, finds them all already managed, and does nothing. Re-running
//     after fixing variables is the intended workflow, not an error path.
//
//   - A match that *is* a create but yields no import ID is returned as
//     unresolved. This is a real problem — the module wants to create a
//     resource that already exists live — so it must be reported rather than
//     dropped, or a later apply would duplicate live infrastructure.
func BuildImportIDs(matched []MatchedImport, creates []PlannedResource, build ImportIDFunc, config map[string]string) (ids map[string]string, unresolved []MatchedImport) {
	createAddrs := make(map[string]bool, len(creates))
	for _, c := range creates {
		createAddrs[c.Address] = true
	}
	ids = make(map[string]string, len(matched))
	for _, m := range matched {
		if !createAddrs[m.Address] {
			continue // already in state; nothing to import
		}
		if build == nil {
			unresolved = append(unresolved, m)
			continue
		}
		id := build(m, config)
		if id == "" {
			unresolved = append(unresolved, m)
			continue
		}
		ids[m.Address] = id
	}
	return ids, unresolved
}

// LiveTypeGroup summarises the unmatched live objects of one resource type.
type LiveTypeGroup struct {
	Type  string
	Count int
	// Names are the objects' display names, sorted.
	Names []string
}

// GroupUnmatchedLive buckets unmatched live objects by resource type, sorted by
// type. Unmatched live objects are worth showing rather than dismissing: most
// are genuinely implicit (peer relations, auto-created secrets, default storage
// pools), but one that *should* have been matched is the signature of a module
// whose topology does not line up with the deployment — typically a count or
// for_each disabled by a variable, so the address the object would map to does
// not exist in the plan.
func GroupUnmatchedLive(live []tfexec.LiveResource) []LiveTypeGroup {
	byType := map[string][]string{}
	for _, lr := range live {
		byType[lr.ResourceType] = append(byType[lr.ResourceType], lr.DisplayName)
	}
	out := make([]LiveTypeGroup, 0, len(byType))
	for typ, names := range byType {
		sort.Strings(names)
		out = append(out, LiveTypeGroup{Type: typ, Count: len(names), Names: names})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Type < out[j].Type })
	return out
}
